language: node_js

sudo: required

node_js:
- 5

services:
- postgresql

before_script:
- cp config-example.json config.json
- psql -c 'create database fuelratstest;' -U postgres
- npm install -g grunt-cli
- sleep 10

notifications:
  irc:
    channels:
      - "irc.fuelrats.com#rattech"
    nick: TravisCI
    template:
          - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{result}"
          - "Change view : %{compare_url}  Build details : %{build_url}"
