language: node_js
node_js:
- 5

services:
- mongodb
- elasticsearch

before_script:
- npm install -g grunt-cli
- sleep 10

notifications:
  irc:
    channels:
      - "irc.fuelrats.com#rattech"
    channel_key: 'whfydaq'
    nick: TravisCI
