language: node_js

branches:
  except:
  - v2

cache:
  directories:
    - node_modules

sudo: false
env:
  - CXX=g++-4.8

addons:
  postgresql: "9.4"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
- 6.3.1

services:
- postgresql

before_script:
- cp config-example.json config.json
- psql -c 'create database fuelratstest;' -U postgres
- psql -c 'create extension citext;' -U postgres fuelratstest
- npm install webpack@^2.1.0-beta
- npm install -g grunt-cli

notifications:
  irc:
    on_success: always
    on_failure: always
    channels:
      - "irc.us.fuelrats.com#rattech"
    nick: TravisCI
    template:
          - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{result}"
          - "Change view : %{compare_url}  Build details : %{build_url}"
