language: node_js
branches:
  except:
  - v2
cache:
  directories:
  - node_modules
sudo: false
env:
- CXX=g++-4.8
addons:
  ssh_known_hosts:
    - cheddar.fuelrats.com
  postgresql: '9.5'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- 8.0.0
services:
- postgresql
before_script:
- psql -c 'create database fuelratstest;' -U postgres
- psql -c 'create extension citext;' -U postgres fuelratstest
- npm install webpack@^2.1.0-beta
- npm install -g grunt-cli
notifications:
  irc:
    on_success: always
    on_failure: always
    channels:
    - irc.us.fuelrats.com#rattech
    nick: TravisCI
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{result}'
    - 'Change view : %{compare_url}  Build details : %{build_url}'
before_deploy:
  - openssl aes-256-cbc -K $encrypted_1c3e6d732708_key -iv $encrypted_1c3e6d732708_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis-deployment@cheddar.fuelrats.com:/var/www/dev.api.fuelrats.com/
  on:
    branch: develop