---
- name: Install forever
  npm:
    name: forever
    global: true
    state: latest
    executable: "{{ npm_binary }}"

- name: Get a list of apps running with forever
  shell: "{{ forever_binary }} list"
  register: forever_list
  changed_when: false

- name: Start the API
  sudo: true
  sudo_user: "{{ user }}"
  shell: "{{ forever_binary }} start /var/www/api/index.js"
  when: "forever_list.stdout.find('/var/www/api/index.js') == -1"

- name: Import archives
  shell: "{{ node_binary }} /var/www/bin/import"
